using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using PoDecath.Sim;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace PoDecath.EditorTools
{
    /// <summary>
    /// Plays every scene in the build list and reports what actually happened.
    ///
    /// The scenes in this project are generated by the <c>PoDecath/*</c> builders and then, mostly, looked
    /// at by hand. That leaves a gap: nothing checks that all seven still enter play mode, spawn their
    /// athletes, load their policies and run for a few seconds without throwing. This closes it. It opens
    /// each scene in turn, plays it for a fixed window, and records every error and exception the runtime
    /// logs, along with enough state to tell a scene that is quietly broken from one that is merely quiet.
    ///
    /// It shares <see cref="GetUpTransferProbe"/>'s architecture and for the same reasons: one
    /// <see cref="EditorApplication.Step"/> per editor update, because the Editor will not advance
    /// play-mode frames unfocused and the Pipeline server aborts main-thread calls that run past five
    /// seconds; and all state in <see cref="SessionState"/>, because entering play mode triggers a domain
    /// reload that would otherwise wipe it.
    ///
    /// On what it does *not* claim
    /// ---------------------------
    /// It does not report a frame rate. Under stepped play mode the editor advances one frame per editor
    /// update, so wall-clock timing measures the stepping loop rather than the game, and a number like
    /// "58 FPS" taken here would be fiction. What it does report -- draw calls, SetPass calls, triangles --
    /// per-rendered-frame and therefore honest. Use the F3 overlay in a normal play session for frame
    /// timing.
    ///
    /// Output: <c>training/logs/scene_sweep.json</c>, plus one PNG per scene beside it.
    /// </summary>
    [InitializeOnLoad]
    public static class SceneSweep
    {
        const string MenuPath = "PoDecath/Sweep All Scenes";

        const string KeyPhase = "PoDecath.Sweep.Phase";
        const string KeyIndex = "PoDecath.Sweep.Index";
        const string KeyFrames = "PoDecath.Sweep.Frames";
        const string KeyT0 = "PoDecath.Sweep.T0";
        const string KeyReport = "PoDecath.Sweep.Report";
        const string KeyErrors = "PoDecath.Sweep.Errors";

        const int WarmupFrames = 60;
        const int MaxLoggedErrors = 12;
        const int MaxLoggedWarnings = 12;

        /// <summary>
        /// No athlete covers this much ground in one fixed step under its own power: at 50 Hz it would be
        /// 37 m/s. A jump larger than this is the race teleporting the athlete back to the start after a
        /// fall or a finish, so it is counted as a reset instead of being added to the distance walked.
        /// </summary>
        const float TeleportStepM = 0.75f;

        /// <summary>Upright dot below which an athlete counts as down, matching the race's own fall test.</summary>
        const float FallenDot = 0.3f;

        /// <summary>An athlete that walked less than this in the whole window did not really run.</summary>
        const float MovedAtAllM = 1.0f;

        /// <summary>
        /// Optional <c>training/logs/scene_sweep_config.json</c>:
        /// <c>{ "seconds": 30.0, "scenes": ["Assets/Scenes/RooftopLap.unity"] }</c>
        ///
        /// Six seconds is enough to prove a scene runs without throwing, and not nearly enough to see
        /// whether an athlete holds a line. A faster policy chasing a carrot that sits a fixed 6 m ahead
        /// gets proportionally less lookahead the quicker it runs, and the rooftop deck is only 5.3 m
        /// wide -- that is a question about a whole lap, not about six seconds.
        /// </summary>
        [Serializable]
        class SweepConfig
        {
            public float seconds = 6f;
            public string[] scenes = null;
        }

        static SweepConfig _cfg;
        static float PlaySeconds => (_cfg ?? LoadConfig()).seconds;

        static string LogDir => Path.Combine(Directory.GetParent(Application.dataPath).FullName,
                                             "training", "logs");
        static string ReportPath => Path.Combine(LogDir, "scene_sweep.json");

        static List<string> _scenes;
        static Dictionary<AthleteRig, Vector3> _startPos = new Dictionary<AthleteRig, Vector3>();
        // Per-rig accumulators. `travelled` used to be `BasePosition - startPos`, which is displacement,
        // not distance: an athlete that completes the 100 m loop arrives back beside its start line and
        // scored ~0 m. A six-second window hid that, because six seconds is not long enough to get round.
        // These accumulate the path actually walked, frame by frame, and survive the reset that ends a
        // fall or a finish.
        static AthleteRig[] _tracked = new AthleteRig[0];
        static Dictionary<AthleteRig, Vector3> _lastPos = new Dictionary<AthleteRig, Vector3>();
        static Dictionary<AthleteRig, float> _pathLen = new Dictionary<AthleteRig, float>();
        static Dictionary<AthleteRig, float> _peakDisp = new Dictionary<AthleteRig, float>();
        static Dictionary<AthleteRig, float> _topSpeed = new Dictionary<AthleteRig, float>();
        static Dictionary<AthleteRig, int> _resets = new Dictionary<AthleteRig, int>();
        static Dictionary<AthleteRig, int> _falls = new Dictionary<AthleteRig, int>();
        static Dictionary<AthleteRig, bool> _wasDown = new Dictionary<AthleteRig, bool>();
        static float _lastT;
        static readonly List<string> _warnings = new List<string>();
        static readonly List<string> _errors = new List<string>();
        static bool _hooked;

        static SceneSweep()
        {
            if (Phase != "idle")
            {
                EditorApplication.update += Tick;
                HookLog();
            }
        }

        static string Phase
        {
            get => SessionState.GetString(KeyPhase, "idle");
            set => SessionState.SetString(KeyPhase, value);
        }

        static List<string> Scenes
        {
            get
            {
                if (_scenes != null) return _scenes;
                var cfg = _cfg ?? LoadConfig();
                _scenes = (cfg.scenes != null && cfg.scenes.Length > 0)
                    ? cfg.scenes.ToList()
                    : EditorBuildSettings.scenes.Where(s => s.enabled).Select(s => s.path).ToList();
                return _scenes;
            }
        }

        static SweepConfig LoadConfig()
        {
            string path = Path.Combine(LogDir, "scene_sweep_config.json");
            try
            {
                if (File.Exists(path))
                    _cfg = JsonUtility.FromJson<SweepConfig>(File.ReadAllText(path)) ?? new SweepConfig();
                else
                    _cfg = new SweepConfig();
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[SceneSweep] could not read {path}: {e.Message}");
                _cfg = new SweepConfig();
            }
            if (_cfg.seconds <= 0f) _cfg.seconds = 6f;
            return _cfg;
        }

        [MenuItem(MenuPath)]
        public static void Start()
        {
            if (Phase != "idle")
            {
                Debug.LogWarning($"[SceneSweep] already running (phase {Phase}).");
                return;
            }
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                Debug.LogError("[SceneSweep] aborted: unsaved scene changes.");
                return;
            }

            Directory.CreateDirectory(LogDir);
            SessionState.SetInt(KeyIndex, 0);
            SessionState.SetString(KeyReport, "");
            SessionState.SetString(KeyErrors, "");
            Phase = "open";
            EditorApplication.update += Tick;
            HookLog();
            Debug.Log($"[SceneSweep] started over {Scenes.Count} scene(s)");
        }

        [MenuItem(MenuPath + " (Abort)")]
        public static void Abort() => Finish("aborted");

        static void HookLog()
        {
            if (_hooked) return;
            Application.logMessageReceived += OnLog;
            _hooked = true;
        }

        static void UnhookLog()
        {
            if (!_hooked) return;
            Application.logMessageReceived -= OnLog;
            _hooked = false;
        }

        static void OnLog(string msg, string stack, LogType type)
        {
            // Warnings are recorded too, separately. A missing reference or a shader fallback logs a
            // warning and nothing else, so a sweep that only watched for errors called those scenes fine.
            if (type == LogType.Warning)
            {
                if (msg.StartsWith("[SceneSweep]") || msg.StartsWith("[GetUpProbe]")) return;
                string w = msg.Replace("\n", " ").Trim();
                if (_warnings.Count < MaxLoggedWarnings && !_warnings.Contains(w)) _warnings.Add(w);
                return;
            }
            if (type != LogType.Error && type != LogType.Exception && type != LogType.Assert) return;
            // The probe's own chatter is not a scene fault.
            if (msg.StartsWith("[SceneSweep]") || msg.StartsWith("[GetUpProbe]")) return;
            string first = (stack ?? "").Split('\n').FirstOrDefault() ?? "";
            string line = $"{type}: {msg.Replace("\n", " ").Trim()}" + (first.Length > 0 ? $"  @ {first.Trim()}" : "");
            if (_errors.Count < MaxLoggedErrors && !_errors.Contains(line))
                _errors.Add(line);
        }

        static void Tick()
        {
            try
            {
                int i = SessionState.GetInt(KeyIndex, 0);
                if (i >= Scenes.Count) { Finish("completed"); return; }

                switch (Phase)
                {
                    case "open":
                        _errors.Clear();
                        EditorSceneManager.OpenScene(Scenes[i], OpenSceneMode.Single);
                        SessionState.SetInt(KeyFrames, 0);
                        Phase = "entering";
                        EditorApplication.EnterPlaymode();
                        return;

                    case "entering":
                        if (EditorApplication.isPlaying && !EditorApplication.isCompiling)
                        {
                            EditorApplication.isPaused = true;
                            SessionState.SetInt(KeyFrames, 0);
                            Phase = "warmup";
                        }
                        return;

                    case "warmup":
                        Step();
                        if (Bump(KeyFrames) >= WarmupFrames)
                        {
                            SessionState.SetFloat(KeyT0, Time.fixedTime);
                            _tracked = UnityEngine.Object
                                .FindObjectsByType<AthleteRig>(FindObjectsSortMode.None)
                                .Where(r => r.IsBound)
                                .ToArray();
                            _startPos = _tracked.ToDictionary(r => r, r => r.BasePosition);
                            _lastPos = _tracked.ToDictionary(r => r, r => r.BasePosition);
                            _pathLen = _tracked.ToDictionary(r => r, r => 0f);
                            _peakDisp = _tracked.ToDictionary(r => r, r => 0f);
                            _topSpeed = _tracked.ToDictionary(r => r, r => 0f);
                            _resets = _tracked.ToDictionary(r => r, r => 0);
                            _falls = _tracked.ToDictionary(r => r, r => 0);
                            _wasDown = _tracked.ToDictionary(r => r, r => r.UprightDot < FallenDot);
                            _lastT = Time.fixedTime;
                            Phase = "playing";
                        }
                        return;

                    case "playing":
                        {
                            Step();
                            Accumulate();
                            float t = Time.fixedTime - SessionState.GetFloat(KeyT0, Time.fixedTime);
                            if (t < PlaySeconds) return;

                            Record(Scenes[i], t);
                            SessionState.SetInt(KeyIndex, i + 1);
                            Phase = "closing";
                            EditorApplication.ExitPlaymode();
                            return;
                        }

                    case "closing":
                        if (!EditorApplication.isPlaying)
                            Phase = "open";
                        return;
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"[SceneSweep] {e.GetType().Name}: {e.Message}");
                AppendReport($"{{\"scene\":\"(sweep)\",\"status\":\"error\",\"error\":\"{Esc(e.Message)}\"}}");
                Finish("error");
            }
        }

        static void Step()
        {
            if (EditorApplication.isPlaying) EditorApplication.Step();
        }

        /// <summary>
        /// Adds one frame of motion to each tracked athlete. Called once per stepped frame, so it sees
        /// the path rather than the endpoints -- the distinction that made a completed lap read as 2.6 m.
        /// </summary>
        static void Accumulate()
        {
            float now = Time.fixedTime;
            float dt = now - _lastT;
            _lastT = now;

            foreach (var r in _tracked)
            {
                if (r == null || !r.IsBound) continue;
                Vector3 p = r.BasePosition;

                if (_lastPos.TryGetValue(r, out Vector3 prev))
                {
                    Vector3 d = p - prev; d.y = 0f;
                    float step = d.magnitude;
                    if (step > TeleportStepM)
                    {
                        // Teleported: a fall reset or a finish reset, not ground covered.
                        _resets[r] = I(_resets, r) + 1;
                    }
                    else
                    {
                        _pathLen[r] = F(_pathLen, r) + step;
                        if (dt > 0f)
                        {
                            float v = step / dt;
                            if (v > F(_topSpeed, r)) _topSpeed[r] = v;
                        }
                    }
                }
                _lastPos[r] = p;

                if (_startPos.TryGetValue(r, out Vector3 p0))
                {
                    Vector3 disp = p - p0; disp.y = 0f;
                    if (disp.magnitude > F(_peakDisp, r)) _peakDisp[r] = disp.magnitude;
                }

                bool down = r.UprightDot < FallenDot;
                bool was = _wasDown.TryGetValue(r, out bool w) && w;
                if (down && !was) _falls[r] = I(_falls, r) + 1;
                _wasDown[r] = down;
            }
        }

        static float F(Dictionary<AthleteRig, float> d, AthleteRig r) => d.TryGetValue(r, out float v) ? v : 0f;
        static int I(Dictionary<AthleteRig, int> d, AthleteRig r) => d.TryGetValue(r, out int v) ? v : 0;

        static int Bump(string key)
        {
            int v = SessionState.GetInt(key, 0) + 1;
            SessionState.SetInt(key, v);
            return v;
        }

        /// <summary>Snapshots what the scene is actually doing, then writes its row of the report.</summary>
        static void Record(string scenePath, float simSeconds)
        {
            var runners = UnityEngine.Object.FindObjectsByType<PolicyRunner>(FindObjectsSortMode.None);
            var rigs = UnityEngine.Object.FindObjectsByType<AthleteRig>(FindObjectsSortMode.None);
            int withModel = runners.Count(r => r.HasModel);
            int bound = rigs.Count(r => r.IsBound);
            int fallen = rigs.Count(r => r.IsBound && r.UprightDot < 0.4f);
            bool nan = rigs.Any(r => r.IsBound && (float.IsNaN(r.BasePosition.x) ||
                                                   float.IsNaN(r.BasePosition.y) ||
                                                   float.IsNaN(r.BasePosition.z)));

            string shot = Path.Combine(LogDir, "sweep_" + Path.GetFileNameWithoutExtension(scenePath) + ".png");
            TryScreenshot(shot);

            var sb = new StringBuilder();
            sb.Append('{');
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"scene\":\"{0}\",", Esc(scenePath));
            float far = 0f, sum = 0f; int n = 0, stalled = 0, totalFalls = 0, totalResets = 0;
            foreach (var r in rigs)
            {
                if (!r.IsBound || !_startPos.ContainsKey(r)) continue;
                float walked = F(_pathLen, r);
                far = Mathf.Max(far, walked); sum += walked; n++;
                totalFalls += I(_falls, r); totalResets += I(_resets, r);
                if (walked < MovedAtAllM) stalled++;
            }

            // "ok" used to mean only "nothing was thrown", which is why a scene whose athletes all stood
            // still, and whose event never left its countdown, still reported ok. Standing still throws
            // nothing. A verdict that cannot say "stalled" is not worth reading.
            string verdict = _errors.Count > 0 ? "errors"
                : (rigs.Length > 0 && bound < rigs.Length) ? "rigs-unbound"
                : (runners.Length > 0 && withModel < runners.Length) ? "policies-missing"
                : nan ? "nan"
                : (n > 0 && stalled > n / 2) ? "stalled"
                : "ok";
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"status\":\"{0}\",", verdict);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"sim_seconds\":{0:0.##},", simSeconds);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"active_scene\":\"{0}\",",
                Esc(UnityEngine.SceneManagement.SceneManager.GetActiveScene().name));
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"policy_runners\":{0},", runners.Length);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"runners_with_model\":{0},", withModel);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"rigs\":{0},", rigs.Length);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"rigs_bound\":{0},", bound);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"rigs_fallen\":{0},", fallen);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"nan_transform\":{0},", nan ? "true" : "false");
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"race\":\"{0}\",", Esc(RacePhase()));

            // How far each athlete actually got, and how quickly. Horizontal only: vertical motion on a
            // rooftop is the athlete bobbing, or falling off, and neither is progress.
            //
            // `walked_m` is the summed path, not the displacement from the start. The two differ by the
            // whole point of a lap: a policy that completes the 100 m loop finishes beside its start line,
            // so the old displacement figure reported it as 2.6 m and a healthy scene looked dead.
            // `net_m` keeps the displacement as well, because for a straight dash the two should agree.

            // Per athlete, because an aggregate cannot tell you which one fell over. Tuning a gait
            // needs to know whether the hand-coded bot is upright and moving, not whether the scene
            // averaged out acceptably.
            sb.Append("\"athletes\":[");
            bool first = true;
            foreach (var r in rigs)
            {
                if (!r.IsBound) continue;
                _startPos.TryGetValue(r, out Vector3 p0);
                Vector3 d = r.BasePosition - p0; d.y = 0f;
                float walked = F(_pathLen, r);
                if (!first) sb.Append(',');
                first = false;
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "{{\"name\":\"{0}\",\"upright\":{1:0.###},\"walked_m\":{2:0.##}," +
                    "\"net_m\":{3:0.##},\"peak_net_m\":{4:0.##},\"mean_speed_mps\":{5:0.##}," +
                    "\"top_speed_mps\":{6:0.##},\"falls\":{7},\"resets\":{8}}}",
                    Esc(RigName(r)), r.UprightDot, walked,
                    d.magnitude, F(_peakDisp, r),
                    simSeconds > 0f ? walked / simSeconds : 0f,
                    F(_topSpeed, r), I(_falls, r), I(_resets, r));
            }
            sb.Append("],");
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"furthest_walked_m\":{0:0.##},", far);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"mean_speed_mps\":{0:0.##},",
                n > 0 && simSeconds > 0f ? (sum / n) / simSeconds : 0f);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"falls\":{0},", totalFalls);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"resets\":{0},", totalResets);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"athletes_that_never_moved\":{0},", stalled);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"draw_calls\":{0},", UnityStats.drawCalls);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"set_pass_calls\":{0},", UnityStats.setPassCalls);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"triangles\":{0},", UnityStats.triangles);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"screenshot\":\"{0}\",", Esc(shot));
            sb.Append("\"warnings\":[");
            sb.Append(string.Join(",", _warnings.Select(e => "\"" + Esc(e) + "\"")));
            sb.Append("],");
            sb.Append("\"errors\":[");
            sb.Append(string.Join(",", _errors.Select(e => "\"" + Esc(e) + "\"")));
            sb.Append("]}");

            // Say it loudly in the console too. A scene that stands still, drops rigs or loses a policy
            // is a failure even though nothing threw, and a report nobody opens is not a report.
            if (verdict != "ok")
                Debug.LogError($"[SceneSweep] {Path.GetFileNameWithoutExtension(scenePath)}: {verdict}");
            else if (stalled > 0 && n > 0)
                Debug.LogWarning($"[SceneSweep] {Path.GetFileNameWithoutExtension(scenePath)}: " +
                                 $"{stalled}/{n} athletes walked under {MovedAtAllM} m in {simSeconds:0.#} s");
            AppendReport(sb.ToString());

            Debug.Log($"[SceneSweep] {Path.GetFileNameWithoutExtension(scenePath)}: " +
                      $"{_errors.Count} error(s), {bound}/{rigs.Length} rigs bound, {withModel}/{runners.Length} policies loaded");
        }

        /// <summary>
        /// The athlete's own name plus which kind of controller is driving it. The importer names the
        /// athlete root after its definition and hangs the rig under it, so walking up to whichever
        /// object carries a runner finds the name a person would recognise.
        /// </summary>
        static string RigName(AthleteRig r)
        {
            Transform t = r.transform;
            for (int i = 0; i < 6 && t != null; i++)
            {
                if (t.GetComponent<HeuristicRunner>() != null) return t.name + " [coded]";
                if (t.GetComponent<PolicyRunner>() != null) return t.name + " [policy]";
                t = t.parent;
            }
            return r.name;
        }

        /// <summary>Whatever race event is in the scene, and what phase it reached.</summary>
        static string RacePhase()
        {
            var ev = UnityEngine.Object.FindAnyObjectByType<RaceEvent>();
            return ev == null ? "(none)" : ev.GetType().Name + ":" + ev.Current;
        }

        static void TryScreenshot(string path)
        {
            try
            {
                var cam = Camera.main ?? UnityEngine.Object.FindAnyObjectByType<Camera>();
                if (cam == null) return;
                var rt = new RenderTexture(960, 540, 24);
                var prev = cam.targetTexture;
                cam.targetTexture = rt;
                cam.Render();
                cam.targetTexture = prev;
                RenderTexture.active = rt;
                var tex = new Texture2D(rt.width, rt.height, TextureFormat.RGB24, false);
                tex.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
                tex.Apply();
                RenderTexture.active = null;
                File.WriteAllBytes(path, tex.EncodeToPNG());
                UnityEngine.Object.DestroyImmediate(tex);
                rt.Release();
                UnityEngine.Object.DestroyImmediate(rt);
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[SceneSweep] screenshot failed: {e.Message}");
            }
        }

        static void AppendReport(string row)
        {
            string cur = SessionState.GetString(KeyReport, "");
            SessionState.SetString(KeyReport, cur.Length == 0 ? row : cur + "," + row);
        }

        static void Finish(string status)
        {
            EditorApplication.update -= Tick;
            UnhookLog();
            string rows = SessionState.GetString(KeyReport, "");
            Directory.CreateDirectory(LogDir);
            File.WriteAllText(ReportPath,
                "{\"status\":\"" + status + "\",\"scenes\":[" + rows + "]}");
            Phase = "idle";
            _scenes = null;
            _cfg = null;
            _startPos.Clear();
            if (EditorApplication.isPlaying) EditorApplication.ExitPlaymode();
            Debug.Log($"[SceneSweep] {status} -> {ReportPath}");
        }

        static string Esc(string s) =>
            (s ?? "").Replace("\\", "/").Replace("\"", "'").Replace("\n", " ").Replace("\r", " ");
    }
}
