using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using PoDecath.Sim;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace PoDecath.EditorTools
{
    /// <summary>
    /// Plays every scene in the build list and reports what actually happened.
    ///
    /// The scenes in this project are generated by the <c>PoDecath/*</c> builders and then, mostly, looked
    /// at by hand. That leaves a gap: nothing checks that all seven still enter play mode, spawn their
    /// athletes, load their policies and run for a few seconds without throwing. This closes it. It opens
    /// each scene in turn, plays it for a fixed window, and records every error and exception the runtime
    /// logs, along with enough state to tell a scene that is quietly broken from one that is merely quiet.
    ///
    /// It shares <see cref="GetUpTransferProbe"/>'s architecture and for the same reasons: one
    /// <see cref="EditorApplication.Step"/> per editor update, because the Editor will not advance
    /// play-mode frames unfocused and the Pipeline server aborts main-thread calls that run past five
    /// seconds; and all state in <see cref="SessionState"/>, because entering play mode triggers a domain
    /// reload that would otherwise wipe it.
    ///
    /// On what it does *not* claim
    /// ---------------------------
    /// It does not report a frame rate. Under stepped play mode the editor advances one frame per editor
    /// update, so wall-clock timing measures the stepping loop rather than the game, and a number like
    /// "58 FPS" taken here would be fiction. What it does report -- draw calls, SetPass calls, triangles --
    /// per-rendered-frame and therefore honest. Use the F3 overlay in a normal play session for frame
    /// timing.
    ///
    /// Output: <c>training/logs/scene_sweep.json</c>, plus one PNG per scene beside it.
    /// </summary>
    [InitializeOnLoad]
    public static class SceneSweep
    {
        const string MenuPath = "PoDecath/Sweep All Scenes";

        const string KeyPhase = "PoDecath.Sweep.Phase";
        const string KeyIndex = "PoDecath.Sweep.Index";
        const string KeyFrames = "PoDecath.Sweep.Frames";
        const string KeyT0 = "PoDecath.Sweep.T0";
        const string KeyReport = "PoDecath.Sweep.Report";
        const string KeyErrors = "PoDecath.Sweep.Errors";

        const int WarmupFrames = 60;
        const int MaxLoggedErrors = 12;

        /// <summary>
        /// Optional <c>training/logs/scene_sweep_config.json</c>:
        /// <c>{ "seconds": 30.0, "scenes": ["Assets/Scenes/RooftopLap.unity"] }</c>
        ///
        /// Six seconds is enough to prove a scene runs without throwing, and not nearly enough to see
        /// whether an athlete holds a line. A faster policy chasing a carrot that sits a fixed 6 m ahead
        /// gets proportionally less lookahead the quicker it runs, and the rooftop deck is only 5.3 m
        /// wide -- that is a question about a whole lap, not about six seconds.
        /// </summary>
        [Serializable]
        class SweepConfig
        {
            public float seconds = 6f;
            public string[] scenes = null;
        }

        static SweepConfig _cfg;
        static float PlaySeconds => (_cfg ?? LoadConfig()).seconds;

        static string LogDir => Path.Combine(Directory.GetParent(Application.dataPath).FullName,
                                             "training", "logs");
        static string ReportPath => Path.Combine(LogDir, "scene_sweep.json");

        static List<string> _scenes;
        static Dictionary<CreatureRig, Vector3> _startPos = new Dictionary<CreatureRig, Vector3>();
        static readonly List<string> _errors = new List<string>();
        static bool _hooked;

        static SceneSweep()
        {
            if (Phase != "idle")
            {
                EditorApplication.update += Tick;
                HookLog();
            }
        }

        static string Phase
        {
            get => SessionState.GetString(KeyPhase, "idle");
            set => SessionState.SetString(KeyPhase, value);
        }

        static List<string> Scenes
        {
            get
            {
                if (_scenes != null) return _scenes;
                var cfg = _cfg ?? LoadConfig();
                _scenes = (cfg.scenes != null && cfg.scenes.Length > 0)
                    ? cfg.scenes.ToList()
                    : EditorBuildSettings.scenes.Where(s => s.enabled).Select(s => s.path).ToList();
                return _scenes;
            }
        }

        static SweepConfig LoadConfig()
        {
            string path = Path.Combine(LogDir, "scene_sweep_config.json");
            try
            {
                if (File.Exists(path))
                    _cfg = JsonUtility.FromJson<SweepConfig>(File.ReadAllText(path)) ?? new SweepConfig();
                else
                    _cfg = new SweepConfig();
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[SceneSweep] could not read {path}: {e.Message}");
                _cfg = new SweepConfig();
            }
            if (_cfg.seconds <= 0f) _cfg.seconds = 6f;
            return _cfg;
        }

        [MenuItem(MenuPath)]
        public static void Start()
        {
            if (Phase != "idle")
            {
                Debug.LogWarning($"[SceneSweep] already running (phase {Phase}).");
                return;
            }
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                Debug.LogError("[SceneSweep] aborted: unsaved scene changes.");
                return;
            }

            Directory.CreateDirectory(LogDir);
            SessionState.SetInt(KeyIndex, 0);
            SessionState.SetString(KeyReport, "");
            SessionState.SetString(KeyErrors, "");
            Phase = "open";
            EditorApplication.update += Tick;
            HookLog();
            Debug.Log($"[SceneSweep] started over {Scenes.Count} scene(s)");
        }

        [MenuItem(MenuPath + " (Abort)")]
        public static void Abort() => Finish("aborted");

        static void HookLog()
        {
            if (_hooked) return;
            Application.logMessageReceived += OnLog;
            _hooked = true;
        }

        static void UnhookLog()
        {
            if (!_hooked) return;
            Application.logMessageReceived -= OnLog;
            _hooked = false;
        }

        static void OnLog(string msg, string stack, LogType type)
        {
            if (type != LogType.Error && type != LogType.Exception && type != LogType.Assert) return;
            // The probe's own chatter is not a scene fault.
            if (msg.StartsWith("[SceneSweep]") || msg.StartsWith("[GetUpProbe]")) return;
            string first = (stack ?? "").Split('\n').FirstOrDefault() ?? "";
            string line = $"{type}: {msg.Replace("\n", " ").Trim()}" + (first.Length > 0 ? $"  @ {first.Trim()}" : "");
            if (_errors.Count < MaxLoggedErrors && !_errors.Contains(line))
                _errors.Add(line);
        }

        static void Tick()
        {
            try
            {
                int i = SessionState.GetInt(KeyIndex, 0);
                if (i >= Scenes.Count) { Finish("completed"); return; }

                switch (Phase)
                {
                    case "open":
                        _errors.Clear();
                        EditorSceneManager.OpenScene(Scenes[i], OpenSceneMode.Single);
                        SessionState.SetInt(KeyFrames, 0);
                        Phase = "entering";
                        EditorApplication.EnterPlaymode();
                        return;

                    case "entering":
                        if (EditorApplication.isPlaying && !EditorApplication.isCompiling)
                        {
                            EditorApplication.isPaused = true;
                            SessionState.SetInt(KeyFrames, 0);
                            Phase = "warmup";
                        }
                        return;

                    case "warmup":
                        Step();
                        if (Bump(KeyFrames) >= WarmupFrames)
                        {
                            SessionState.SetFloat(KeyT0, Time.fixedTime);
                            _startPos = UnityEngine.Object
                                .FindObjectsByType<CreatureRig>(FindObjectsSortMode.None)
                                .Where(r => r.IsBound)
                                .ToDictionary(r => r, r => r.BasePosition);
                            Phase = "playing";
                        }
                        return;

                    case "playing":
                        {
                            Step();
                            float t = Time.fixedTime - SessionState.GetFloat(KeyT0, Time.fixedTime);
                            if (t < PlaySeconds) return;

                            Record(Scenes[i], t);
                            SessionState.SetInt(KeyIndex, i + 1);
                            Phase = "closing";
                            EditorApplication.ExitPlaymode();
                            return;
                        }

                    case "closing":
                        if (!EditorApplication.isPlaying)
                            Phase = "open";
                        return;
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"[SceneSweep] {e.GetType().Name}: {e.Message}");
                AppendReport($"{{\"scene\":\"(sweep)\",\"status\":\"error\",\"error\":\"{Esc(e.Message)}\"}}");
                Finish("error");
            }
        }

        static void Step()
        {
            if (EditorApplication.isPlaying) EditorApplication.Step();
        }

        static int Bump(string key)
        {
            int v = SessionState.GetInt(key, 0) + 1;
            SessionState.SetInt(key, v);
            return v;
        }

        /// <summary>Snapshots what the scene is actually doing, then writes its row of the report.</summary>
        static void Record(string scenePath, float simSeconds)
        {
            var runners = UnityEngine.Object.FindObjectsByType<PolicyRunner>(FindObjectsSortMode.None);
            var rigs = UnityEngine.Object.FindObjectsByType<CreatureRig>(FindObjectsSortMode.None);
            int withModel = runners.Count(r => r.HasModel);
            int bound = rigs.Count(r => r.IsBound);
            int fallen = rigs.Count(r => r.IsBound && r.UprightDot < 0.4f);
            bool nan = rigs.Any(r => r.IsBound && (float.IsNaN(r.BasePosition.x) ||
                                                   float.IsNaN(r.BasePosition.y) ||
                                                   float.IsNaN(r.BasePosition.z)));

            string shot = Path.Combine(LogDir, "sweep_" + Path.GetFileNameWithoutExtension(scenePath) + ".png");
            TryScreenshot(shot);

            var sb = new StringBuilder();
            sb.Append('{');
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"scene\":\"{0}\",", Esc(scenePath));
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"status\":\"{0}\",",
                _errors.Count > 0 ? "errors" : "ok");
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"sim_seconds\":{0:0.##},", simSeconds);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"active_scene\":\"{0}\",",
                Esc(UnityEngine.SceneManagement.SceneManager.GetActiveScene().name));
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"policy_runners\":{0},", runners.Length);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"runners_with_model\":{0},", withModel);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"rigs\":{0},", rigs.Length);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"rigs_bound\":{0},", bound);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"rigs_fallen\":{0},", fallen);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"nan_transform\":{0},", nan ? "true" : "false");

            // How far each athlete actually got, and how quickly. Horizontal only: vertical motion on a
            // rooftop is the athlete bobbing, or falling off, and neither is progress.
            float far = 0f, sum = 0f; int n = 0;
            foreach (var r in rigs)
            {
                if (!r.IsBound || !_startPos.TryGetValue(r, out Vector3 p0)) continue;
                Vector3 d = r.BasePosition - p0; d.y = 0f;
                float dist = d.magnitude;
                far = Mathf.Max(far, dist); sum += dist; n++;
            }
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"furthest_m\":{0:0.##},", far);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"mean_speed_mps\":{0:0.##},",
                n > 0 && simSeconds > 0f ? (sum / n) / simSeconds : 0f);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"draw_calls\":{0},", UnityStats.drawCalls);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"set_pass_calls\":{0},", UnityStats.setPassCalls);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"triangles\":{0},", UnityStats.triangles);
            sb.AppendFormat(CultureInfo.InvariantCulture, "\"screenshot\":\"{0}\",", Esc(shot));
            sb.Append("\"errors\":[");
            sb.Append(string.Join(",", _errors.Select(e => "\"" + Esc(e) + "\"")));
            sb.Append("]}");
            AppendReport(sb.ToString());

            Debug.Log($"[SceneSweep] {Path.GetFileNameWithoutExtension(scenePath)}: " +
                      $"{_errors.Count} error(s), {bound}/{rigs.Length} rigs bound, {withModel}/{runners.Length} policies loaded");
        }

        static void TryScreenshot(string path)
        {
            try
            {
                var cam = Camera.main ?? UnityEngine.Object.FindAnyObjectByType<Camera>();
                if (cam == null) return;
                var rt = new RenderTexture(960, 540, 24);
                var prev = cam.targetTexture;
                cam.targetTexture = rt;
                cam.Render();
                cam.targetTexture = prev;
                RenderTexture.active = rt;
                var tex = new Texture2D(rt.width, rt.height, TextureFormat.RGB24, false);
                tex.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
                tex.Apply();
                RenderTexture.active = null;
                File.WriteAllBytes(path, tex.EncodeToPNG());
                UnityEngine.Object.DestroyImmediate(tex);
                rt.Release();
                UnityEngine.Object.DestroyImmediate(rt);
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[SceneSweep] screenshot failed: {e.Message}");
            }
        }

        static void AppendReport(string row)
        {
            string cur = SessionState.GetString(KeyReport, "");
            SessionState.SetString(KeyReport, cur.Length == 0 ? row : cur + "," + row);
        }

        static void Finish(string status)
        {
            EditorApplication.update -= Tick;
            UnhookLog();
            string rows = SessionState.GetString(KeyReport, "");
            Directory.CreateDirectory(LogDir);
            File.WriteAllText(ReportPath,
                "{\"status\":\"" + status + "\",\"scenes\":[" + rows + "]}");
            Phase = "idle";
            _scenes = null;
            _cfg = null;
            _startPos.Clear();
            if (EditorApplication.isPlaying) EditorApplication.ExitPlaymode();
            Debug.Log($"[SceneSweep] {status} -> {ReportPath}");
        }

        static string Esc(string s) =>
            (s ?? "").Replace("\\", "/").Replace("\"", "'").Replace("\n", " ").Replace("\r", " ");
    }
}
