"""Compare the MuJoCo Warp and Isaac Lab runs of the same task from their TensorBoard logs.

    .venv/Scripts/python.exe compare.py            # prints a table and writes DOCS/COMPARISON.md

Both trainers log under training/logs/tb. Metrics are read from the event files (no live processes).
"""
from __future__ import annotations

import glob
import os
from typing import Dict, List, Tuple

from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

HERE = os.path.dirname(os.path.abspath(__file__))
TB = os.path.join(HERE, "logs", "tb")
DOCS = os.path.join(HERE, "..", "DOCS", "COMPARISON_TABLE.md")   # COMPARISON.md holds the written analysis


def load(run_dir: str) -> Dict[str, List[Tuple[float, int, float]]]:
    acc = EventAccumulator(run_dir, size_guidance={"scalars": 0})
    acc.Reload()
    out = {}
    for tag in acc.Tags().get("scalars", []):
        out[tag] = [(e.wall_time, e.step, e.value) for e in acc.Scalars(tag)]
    return out


def first_step_where(series, pred):
    for _, step, v in series:
        if pred(v):
            return step
    return None


def summarize(name: str, run_dir: str, tags: Dict[str, str]) -> Dict[str, object]:
    s = load(run_dir)
    def get(key):
        t = tags.get(key)
        return s.get(t, []) if t else []
    fps = get("fps"); vel = get("vel"); ep_len = get("ep_len"); fall = get("fall")
    walls = [w for series in s.values() for (w, _, _) in series]
    wall_min = (max(walls) - min(walls)) / 60.0 if walls else 0.0
    main_series = ep_len or fps
    res = {
        "run": name,
        "dir": os.path.basename(run_dir),
        "iterations": max((st for (_, st, _) in main_series), default=0),
        "wall_min": round(wall_min, 1),
        "mean_sps": round(sum(v for _, _, v in fps) / len(fps)) if fps else None,
        "final_speed": round(sum(v for _, _, v in vel[-10:]) / max(1, len(vel[-10:])), 2) if vel else None,
        "final_ep_len": round(sum(v for _, _, v in ep_len[-10:]) / max(1, len(ep_len[-10:])), 1) if ep_len else None,
        "iter_to_ep_len_18s": first_step_where(ep_len, lambda v: v >= 18.0) if ep_len else None,
        # ignore the first iterations, where no episode has ended yet and the fall rate reads 0
        "iter_to_fall_lt_5pct": first_step_where([e for e in fall if e[1] >= 50], lambda v: v < 0.05) if fall else None,
    }
    return res


def main() -> None:
    mj = sorted(glob.glob(os.path.join(TB, "run_to_target_*")))
    isaac = sorted(glob.glob(os.path.join(TB, "isaac_run_to_target_*")))
    rows = []
    if mj:
        rows.append(summarize("MuJoCo Warp + custom PPO", mj[-1],
                              {"fps": "perf/fps", "vel": "env/v_toward", "ep_len": "env/ep_len_s", "fall": "env/fall_rate"}))
    if isaac:
        # rsl_rl tags: Perf/total_fps, Train/mean_episode_length (steps at 50 Hz), Episode/... none for velocity
        r = summarize("Isaac Lab (PhysX) + rsl_rl PPO", isaac[-1],
                      {"fps": "Perf/total_fps", "ep_len": "Train/mean_episode_length"})
        if r["final_ep_len"] is not None:
            r["final_ep_len"] = round(r["final_ep_len"] / 50.0, 1)   # steps -> seconds
            s = load(isaac[-1]).get("Train/mean_episode_length", [])
            r["iter_to_ep_len_18s"] = first_step_where(s, lambda v: v >= 18.0 * 50)
        rows.append(r)
    keys = ["run", "iterations", "wall_min", "mean_sps", "final_speed", "final_ep_len", "iter_to_ep_len_18s", "iter_to_fall_lt_5pct"]
    lines = ["| " + " | ".join(keys) + " |", "|" + "---|" * len(keys)]
    for r in rows:
        lines.append("| " + " | ".join(str(r.get(k, "")) for k in keys) + " |")
    table = "\n".join(lines)
    print(table)
    os.makedirs(os.path.dirname(DOCS), exist_ok=True)
    with open(DOCS, "w", encoding="utf-8") as f:
        f.write("# MuJoCo Warp vs Isaac Lab on the same athlete\n\n")
        f.write("Same MJCF body, PD gains, 75-float observation, 21 actions, reward terms, 4096 environments, "
                "24 steps per iteration, PPO with the same hyper-parameters. Generated by training/compare.py.\n\n")
        f.write(table + "\n\n")
        f.write("Columns: wall_min = wall-clock minutes; mean_sps = control steps per second; final_speed = mean velocity "
                "toward the target (m/s, MuJoCo run only, Isaac run logs episode length); final_ep_len = mean episode "
                "length in seconds (20 = never fell); iter_to_* = first iteration reaching the milestone.\n")
    print(f"wrote {os.path.abspath(DOCS)}")


if __name__ == "__main__":
    main()
